name: Discover any missing version and create a git tag for it

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Discover missing versions and push git tags
        run: |
          python build_missing_versions.py

