name: Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `1.2.3` tags as releases.
    tags:
      - "*"


env:
  IMAGE_NAME: mlflow

jobs:
  push-to-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}
          tag_with_ref: true
          add_git_labels: true

